//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FCLAO021:"Insuarance Master Maintenance",FCLAO022:"Function Code",FCLAO041:"CIF Id",FCLAO023:"Inuarance Id",FCLAO024:"Asset Group Id",FCLAO025:"Asset Id",FCLAO026:"Inuarance Done By",FCLAO027:"Insuarance Policy No.",FCLAO028:"Insuarance Company",FCLAO029:"Policy Type",FCLAO030:"Asset Value",FCLAO031:"Policy Start Date",FCLAO032:"Policy End Date",FCLAO033:"Cover Note No.",FCLAO034:"Cover Note Expiry Date",FCLAO035:"Premium Amt.",FCLAO036:"Insuarance Credit Amt.",FCLAO037:"Capitalized Amt.",FCLAO038:"Credit Period(Days)",FCLAO039:"Sum Insured Amount",FCLAO040:"Commission Amount",FCDET002:"Submit",FCDET003:"Validate",FCDET004:"Cancel",FCDET014:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
