var jspRes={FCLAO002:"Insuarance Master Maintenance",FCLAO003:"Function Code",FCLAO004:"A-Add",FCLAO005:"I-Inquiry",FCLAO006:"M-Modify",FCLAO007:"X-Cancel",FCLAO008:"D-Delete",FCLAO009:"V-Verify",FCLAO010:"N-Renew",FCLAO011:"Insuarance Id",FCLAO012:"Asset Group Id",FCLAO013:"Asset Id",FCLAO014:"Insuarance Done By",FCLAO050:"BY SLFL",FCLAO051:"SLFL ON CREDIT",FCLAO052:"DIRECT BY APPLICANT ON CREDIT",FCLAO053:"EXISTING SLF",FCLAO060:"CIF Id",FCLAO054:"DIRECT INSUARANCE PAID",FCLAO055:"FREE INSUARANCE GIVEN BY SALE",FCLAO016:"Submit",FCLAO017:"Cancel",FCLAO018:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);