var jspRes={FCLAO002:"Insurance Master Maintenance",FCLAO003:"Function Code",FCLAO004:"A-Add",FCLAO005:"I-Inquiry",FCLAO006:"M-Modify",FCLAO007:"X-Cancel",FCLAO008:"D-Delete",FCLAO009:"V-Verify",FCLAO010:"N-Renew",FCLAO011:"Insurance Id",FCLAO012:"Asset Group Id",FCLAO013:"Asset Id",FCLAO014:"Insurance Done By",FCLAO050:"BY SFP",FCLAO051:"SFP ON CREDIT",FCLAO052:"DIRECT BY APPLICANT ON CREDIT",FCLAO053:"EXISTING SFP",FCLAO020:"Search Criteria",FCLAO021:"CHASSIS NO",FCLAO023:"Search Value",FCLAO022:"VEHICLE NO",FCLAO024:"ENGINE NO",FCLAO060:"CIF Id",FCLAO054:"DIRECT INSURANCE PAID",FCLAO055:"FREE INSURANCE GIVEN BY SALE",FCLAO016:"Submit",FCLAO017:"Cancel",FCLAO018:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);