<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />
<jsp:include page="l6_tableStyle.css"/>

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= '<%= ParseValue.checkString((securityInfo.bodDate).substring(0,10))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var cifId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cifId",""))%>';
	var assetId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".assetId",""))%>';
	var assetGrpId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".assetGrpId",""))%>';
	var assetValue = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".assetValue",""))%>';
	var insProvider = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insProvider",""))%>';
	var insProviderTxt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insProviderTxt",""))%>';
	var insId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insId",""))%>';
	var insPolicyNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insPolicyNo",""))%>';
	var insName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insName",""))%>';
	var policyType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".policyType",""))%>';
	var startDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".startDate",""))%>';
	var endDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".endDate",""))%>';
	var noteNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteNo",""))%>';
	var expiryDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".expiryDate",""))%>';
	var premiumAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".premiumAmt",""))%>';
	var credAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".credAmt",""))%>';
	var capAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".capAmt",""))%>';
	var credPeriod = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".credPeriod",""))%>';
	var insAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insAmt",""))%>';
	var comissionAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".comissionAmt",""))%>';
	var insCover1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover1",""))%>';
	var insCover2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover2",""))%>';
	var insCover3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover3",""))%>';
	var insCover4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover4",""))%>';
	var insCover5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover5",""))%>';
	var insCover6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover6",""))%>';
	var insCover7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover7",""))%>';
	var insCover8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover8",""))%>';
	var insCover9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover9",""))%>';
	var insCover10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover10",""))%>';
	var insCover11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover11",""))%>';
	var insCover12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover12",""))%>';
	var insCover13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover13",""))%>';
	var insCover14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover14",""))%>';
	var insCover15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover15",""))%>';
	var insCover16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".insCover16",""))%>';
	var policyDescA = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".policyDescA",""))%>';
	var term = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".term",""))%>';
	
</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCustId.js",sProfileId)%>" > </script>
<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

